version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: test_db
    networks:
      - test_db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    depends_on:
      - dev-db
    environment:
      DB_HOST: dev-db
      DB_USER: postgres
      DB_PASSWORD: secretpass
      DB_PORT: 5432
      DB_NAME: test_db
      JWT_SECRET: sajjdwsbciw2o3i02jdj021oeqjw
      JWT_EXPIRES_IN: 10d
    networks:
      - test_db
networks:
  test_db:
